name: Send Telegram Anniversary Message

on:
  schedule:
    - cron: "0 0 12 * *"  # At 00:00 UTC on the 12th day of every month

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Call Telegram Bot API
        run: curl -s https://your-project.vercel.app/api/send-message
